# Generated by Django 2.2 on 2025-08-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('place', models.TextField()),
                ('landmark', models.TextField()),
                ('payment_type', models.BooleanField(default=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
