# Generated by Django 2.2 on 2025-08-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250822_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
