# Generated by Django 2.2 on 2025-08-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250827_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
