# Generated by Django 2.2 on 2025-08-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250827_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='address',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
