# Generated by Django 2.2 on 2025-08-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250828_1612'),
        ('cart', '0002_item_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_Order_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=None)),
                ('payment_type', models.BooleanField(default=True)),
                ('ADDRESS', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
                ('ITEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Item')),
            ],
        ),
    ]
