# Generated by Django 2.2 on 2025-07-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='CATEGORY',
        ),
    ]
