# Generated by Django 2.2 on 2025-08-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250827_1737'),
        ('shop', '0005_order_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_summary',
            name='USER',
        ),
        migrations.AddField(
            model_name='order_summary',
            name='ADDRESS',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address'),
        ),
    ]
