# Generated by Django 2.2 on 2025-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20250827_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_summary',
            name='payment_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order_summary',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
